version: '3'
services:
  db:
    image: mysql:5.7
    command: ["--innodb_use_native_aio=0", "--default-authentication-plugin=mysql_native_password"]
    restart: always
    env_file:
      - .env
  server:
    depends_on:
      - db
    env_file:
      - .env
      - node.env
    build:
        dockerfile: test.Dockerfile
